export const BASE_URL = 'http://127.0.0.1:8000'
export const GET_WORKSPACES_API = 'workspaces'
export const GET_DATASETS_API = 'datasets'
export const CREATE_WORKSPACE_API = 'workspace'
export const ADD_DOCUMENTS_API = 'add_documents'
export const ADUTHENTICATE_API = 'users/authenticate' 