export const BASE_URL = 'https://sleuth-ui-backend-dev.ris2-debater-event.us-east.containers.appdomain.cloud'
export const GET_WORKSPACES_API = 'workspaces'
export const GET_DATASETS_API = 'datasets'
export const WORKSPACE_API = 'workspace'
export const CREATE_WORKSPACE_API = 'workspace'
export const ADD_DOCUMENTS_API = 'add_documents'
export const ADUTHENTICATE_API = 'users/authenticate'
