export const {
  currentContentData,
  currentPage,
  isPaginationRequired,
  pageCount,
  goToPreviousPage,
  goToNextPage,
} = {
  goToPreviousPage: () => {},
  goToNextPage: () => {},
  currentContentData: [
    {
      docId: "med-Troglocyclocheilus khammouanensis",
      id: "med-Troglocyclocheilus khammouanensis-1",
      modelPrediction: "pos",
      userLabel: "pos",
      text: "Troglocyclocheilus khammouanensis is a species of cyprinid fish found in caves in Laos.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Starry weever",
      id: "med-Starry weever-4",
      modelPrediction: "pos",
      userLabel: "none",
      text: "The eyes are small, the snout is short and blunt, and the operculum bears a robust venomous spine.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Starry weever",
      id: "med-Starry weever-5",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Five fan-shaped groups of bony ridges are on the top of the head just behind the eye.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Starry weever",
      id: "med-Starry weever-8",
      modelPrediction: "pos",
      userLabel: "none",
      text: "This fish can grow to a maximum length around , but a more common length is .",
      snippet: null,
      otherUserLabels: {
        "0": "pos",
      },
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Starry weever",
      id: "med-Starry weever-12",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Poison glands are located at the base of this fin and on the spine on the gill cover.",
      snippet: null,
      otherUserLabels: {
        "0": "pos",
      },
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Starry weever",
      id: "med-Starry weever-14",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Its diet consists largely of shrimp and other crustaceans, and small fish.",
      snippet: null,
      otherUserLabels: {
        "0": "pos",
      },
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Guinean weever",
      id: "med-Guinean weever-0",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Guinean weever",
      snippet: null,
      otherUserLabels: {
        "0": "pos",
      },
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Notomyxine tridentiger",
      id: "med-Notomyxine tridentiger-15",
      modelPrediction: "pos",
      userLabel: "none",
      text: "If none develops, then the animal becomes sterile.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Notomyxine tridentiger",
      id: "med-Notomyxine tridentiger-16",
      modelPrediction: "pos",
      userLabel: "none",
      text: "If both anterior and posterior parts develop, then the animal becomes a functional hermaphrodite.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Japanese anchovy",
      id: "med-Japanese anchovy-0",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Japanese anchovy",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Parides gundlachianus",
      id: "med-Parides gundlachianus-11",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Occurs in the mountainous eastern part of the island, especially near the coast, where it is met with on flowers, and sometimes also drinking at pools.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Spinachia spinachia",
      id: "med-Spinachia spinachia-5",
      modelPrediction: "pos",
      userLabel: "none",
      text: "The fifteen-spined stickleback is an elongated fish with a long slender snout, an elongated caudal peduncle about one third of the total length, and a fan-like rounded caudal fin.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Spinachia spinachia",
      id: "med-Spinachia spinachia-10",
      modelPrediction: "pos",
      userLabel: "none",
      text: "It grows to a maximum size of ,",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Apeltes",
      id: "med-Apeltes-3",
      modelPrediction: "pos",
      userLabel: "none",
      text: "It generally has either four or five dorsal spines but may have as many as seven.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Apeltes",
      id: "med-Apeltes-19",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Males establish territories and construct nests out of vegetation either on the bottom or on underwater structures, and may construct as many as five nests stacked in a tiered effect.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Apeltes",
      id: "med-Apeltes-21",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Females may produce several clutches of eggs per year.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Electraglaia nigrapex",
      id: "med-Electraglaia nigrapex-1",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Electraglaia nigrapex is a moth of the family Tortricidae which is endemic to Vietnam.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Electraglaia nigrapex",
      id: "med-Electraglaia nigrapex-6",
      modelPrediction: "pos",
      userLabel: "none",
      text: 'The specific name refers to the colouration of the forewing apex and is derived from Latin "niger" (meaning black).',
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Papilio diophantus",
      id: "med-Papilio diophantus-5",
      modelPrediction: "pos",
      userLabel: "none",
      text: 'Posterior wing with a tail more spatulate than in "P. Helenus", and tipped with cream colour,marked from the costal margin to the third hranch of the median nervule by a large cream-coloured spot, divided by the nervures into four parts, the lowest much smaller and more lunular than the other three parts.',
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Diplocalyptis ferruginimixta",
      id: "med-Diplocalyptis ferruginimixta-1",
      modelPrediction: "pos",
      userLabel: "pos",
      text: "Diplocalyptis ferruginimixta is a moth of the family Tortricidae which is endemic to Vietnam.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Diplocalyptis triangulifera",
      id: "med-Diplocalyptis triangulifera-1",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Diplocalyptis triangulifera is a moth of the family Tortricidae which is endemic to Vietnam.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Diplocalyptis triangulifera",
      id: "med-Diplocalyptis triangulifera-7",
      modelPrediction: "pos",
      userLabel: "none",
      text: 'The specific name refers to the subterminal blotch of the forewing and is derived from Latin "triangulum" (meaning triangle) and "ferre" (meaning I carry).',
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Adoxophyes afonini",
      id: "med-Adoxophyes afonini-1",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Adoxophyes afonini is a moth of the family Tortricidae which is endemic to Vietnam.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Adoxophyes afonini",
      id: "med-Adoxophyes afonini-6",
      modelPrediction: "pos",
      userLabel: "none",
      text: "The species is dedicated to Mr. Afonin, the collector of the species.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Kennelia tropica",
      id: "med-Kennelia tropica-1",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Kennelia tropica is a moth of the family Tortricidae which is endemic to Vietnam.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Eucoenogenes atripalpa",
      id: "med-Eucoenogenes atripalpa-1",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Eucoenogenes atripalpa is a moth of the family Tortricidae that is endemic to Vietnam.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Eucoenogenes sipanga",
      id: "med-Eucoenogenes sipanga-1",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Eucoenogenes sipanga is a moth of the family Tortricidae that is endemic to Vietnam.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Acrobrycon",
      id: "med-Acrobrycon-1",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Acrobrycon is a genus of characin found in tropical South America.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Agoniates",
      id: "med-Agoniates-2",
      modelPrediction: "pos",
      userLabel: "none",
      text: "There are currently two recognized species in this genus:",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Aphyocharacidium",
      id: "med-Aphyocharacidium-1",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Aphyocharacidium is a genus of characin found in tropical South America, with two currently described species:",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Enneapterygius clea",
      id: "med-Enneapterygius clea-2",
      modelPrediction: "pos",
      userLabel: "none",
      text: "It is endemic to Queensland, Australia.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Enneapterygius clea",
      id: "med-Enneapterygius clea-4",
      modelPrediction: "pos",
      userLabel: "none",
      text: 'He gave the blenny its species epithet, "clea", and its common name in honour of his daughter Clea, then seven years old.',
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Syngnathus dawsoni",
      id: "med-Syngnathus dawsoni-2",
      modelPrediction: "pos",
      userLabel: "none",
      text: "It occurs in the central, western Atlantic in the Caribbean Sea from Puerto Rico to St. Lucia and has been recorded only from the east of the Mona Passage.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Syngnathus dawsoni",
      id: "med-Syngnathus dawsoni-3",
      modelPrediction: "pos",
      userLabel: "none",
      text: "It is a marine tropical demersal fish.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Syngnathus dawsoni",
      id: "med-Syngnathus dawsoni-6",
      modelPrediction: "pos",
      userLabel: "none",
      text: "The specific name honours Charles Eric Dawson who collected the type material and who recognised this species as different from the other Atlantic members of the family Syngnathidae.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Odostomia limpida",
      id: "med-Odostomia limpida-7",
      modelPrediction: "pos",
      userLabel: "none",
      text: "The base of the body whorl is large, rounded, very narrowly umbilicated.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Danionin",
      id: "med-Danionin-4",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Many species are brightly coloured and are available as aquarium fish worldwide.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Danionin",
      id: "med-Danionin-10",
      modelPrediction: "pos",
      userLabel: "none",
      text: 'Nearly all the fish classed within the genera "Danio" and "Devario" were originally placed in the genus "Danio" upon discovery.',
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Danionin",
      id: "med-Danionin-12",
      modelPrediction: "pos",
      userLabel: "none",
      text: 'The sole species within Myers\' "Daniops", "D. myersi", has long ago been found to be a synonym of "Devario laoensis", but his genus "Brachydanio" lasted for much longer, as it included most of the fish now classed as "Danio", whereas "Danio" included most of the fish now classed as "Devario".',
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Danionin",
      id: "med-Danionin-13",
      modelPrediction: "pos",
      userLabel: "none",
      text: 'However, "Danio dangila" and "Danio feegradei", both of which had most of the characteristics of the "Brachydanio" (with the exception that they were much larger than "Brachydanio" species) were placed within "Danios".',
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Danionin",
      id: "med-Danionin-14",
      modelPrediction: "pos",
      userLabel: "none",
      text: '(Due to this and other misplacing, both "Danio" and "Brachydanio" were found to be paraphyletic by Fang Fang in 2003.).',
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Danionin",
      id: "med-Danionin-15",
      modelPrediction: "pos",
      userLabel: "none",
      text: 'In 1941, H.M. Smith attempted to unite all the "Brachydanios" and "Danios" species into one genus on the basis of a fish from Thailand which was supposed to bridge the gap.',
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Danionin",
      id: "med-Danionin-18",
      modelPrediction: "pos",
      userLabel: "none",
      text: 'In this scheme, danionins were distinguished from other cyprinids by the uniquely shared character of the "danionin notch", a large and peculiarly shaped indentation in the medial margin of the mandibles; this feature is not noted in rasborins, esomins, bariliins, or chelins.',
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Danionin",
      id: "med-Danionin-20",
      modelPrediction: "pos",
      userLabel: "none",
      text: '"Microrasbora" was not considered to be a part of the danionins, nor even closely related to "Danionella", a part of the danionins as understood at that time.',
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Danionin",
      id: "med-Danionin-21",
      modelPrediction: "pos",
      userLabel: "none",
      text: 'In the late 1980s and 1990s, doubts grew about the validity of "Brachydanio", with species being referred to their original naming of "Danio", and Fang Fang determined that the genus "Danio", recognized up to that point, was paraphyletic.',
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Danionin",
      id: "med-Danionin-24",
      modelPrediction: "pos",
      userLabel: "none",
      text: 'As "D. dangila" was the first discovered "Danio" (or type) the name "Danio" had to remain with "D. dangila", which is why the vast majority of species were moved to "Devario".',
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Danionin",
      id: "med-Danionin-33",
      modelPrediction: "pos",
      userLabel: "none",
      text: "The fish of Rasborinae almost invariably have anal fins with three spines and five rays.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Danionin",
      id: "med-Danionin-43",
      modelPrediction: "pos",
      userLabel: "none",
      text: '"Tanichthys" is often regarded as a danionin by aquarists and grouped as such in some older aquatic publications, but no scientific basis exists for this, a fact stated on numerous occasions by Brittan and others.',
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Danionin",
      id: "med-Danionin-52",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Although boisterous and liable to chase each other and other fish, they are good community fish and do not generally attack each other or other fish, although they occasionally nip fins, and like most fish, eat eggs and any fish small enough to fit into their mouths.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
    {
      docId: "med-Danionin",
      id: "med-Danionin-57",
      modelPrediction: "pos",
      userLabel: "none",
      text: "Since 2004, many new danionins have been discovered which do not yet have scientific names and many other species, previously known only to the scientific fraternity, have become available in aquarist shops.",
      snippet: null,
      otherUserLabels: {},
      multiclassUserLabel: null,
      multiclassModelPrediction: null,
    },
  ],
  currentPage: 1,
  isPaginationRequired: true,
  pageCount: 272,
};
