export const SEARCH_ALL_DOCS_TOOLTIP_MSG = 'Search all documents'
export const NEXT_TO_LABEL_TOOLTIP_MSG = 'Recommended to label' 
export const PREV_DOC_TOOLTIP_MSG = "Go to previous document"
export const NEXT_DOC_TOOLTIP_MSG = "Go to next document"
export const LOGOUT_TOOLTIP_MSG = "Logout"
export const GO_TO_WORKSPACE_CONFIG_TOOLTIP_MSG = "Go to workspace configuration"
export const NO_MODEL_AVAILABLE_MSG = "not available yet"
export const CREATE_NEW_CATEGORY_MODAL_MSG = "Create a new category"
export const CREATE_NEW_CATEGORY_TOOLTIP_MSG = "Create new category"
export const CREATE_NEW_CATEGORY_PLACEHOLDER_MSG = "New category name"
export const SEARCH = 'search'
export const RCMD = 'rcmd'
export const RIGHT_DRAWER_WIDTH = 360